[package]
name = "file_gen"
version = "0.1.0"
authors = ["Brian L. Troutwine <brian@troutwine.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"

[dependencies.tracing]
version = "0.1"
default-features = false
features = ["std", "attributes"]

[dependencies.tracing-subscriber]
version = "0.2"
default-features = false
features = ["fmt", "json", "chrono", "parking_lot"]

[dependencies.byte-unit]
version = "4.0"
default-features = false
features = []

[dependencies.governor]
version = "0.3"
default-features = false
features = ["std", "dashmap", "jitter", "quanta"]

[dependencies.argh]
version = "0.1"
default-features = false
features = []

[dependencies.fastrand]
version = "1.4"
default-features = false
features = []

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive", "std"]

[dependencies.futures]
version = "0.3"
default-features = false
features = ["std"]

[dependencies.tokio]
version = "1.2"
default-features = false
features = ["rt", "macros", "fs", "io-util"]

[profile.release]
lto = true        # Optimize our binary at link stage.
codegen-units = 1 # Increases compile time but improves optmization alternatives.
debug = true      # Include debug symbols in the executable, benefits tooling.
opt-level = 3     # Optimize with 'all' optimization flipped on. May produce larger binaries than 's' or 'z'.
